# CMake generated Testfile for 
# Source directory: /home/ck/桌面/ns/ns-3.37/src/tap-bridge/examples
# Build directory: /home/ck/桌面/ns/ns-3.37/src/tap-bridge/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-tap-csma "ns3-dev-tap-csma-default")
set_tests_properties(ctest-tap-csma PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/tap-bridge/examples/CMakeLists.txt;2;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-csma-virtual-machine "ns3-dev-tap-csma-virtual-machine-default")
set_tests_properties(ctest-tap-csma-virtual-machine PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/tap-bridge/examples/CMakeLists.txt;12;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-wifi-virtual-machine "ns3-dev-tap-wifi-virtual-machine-default")
set_tests_properties(ctest-tap-wifi-virtual-machine PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/tap-bridge/examples/CMakeLists.txt;21;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-wifi-dumbbell "ns3-dev-tap-wifi-dumbbell-default")
set_tests_properties(ctest-tap-wifi-dumbbell PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/tap-bridge/examples/CMakeLists.txt;32;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/tap-bridge/examples/CMakeLists.txt;0;")
