# CMake generated Testfile for 
# Source directory: /home/ck/桌面/ns/ns-3.37/src/energy/examples
# Build directory: /home/ck/桌面/ns/ns-3.37/src/energy/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-generic-battery-discharge-example "ns3-dev-generic-battery-discharge-example-default")
set_tests_properties(ctest-generic-battery-discharge-example PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/energy/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/energy/examples/CMakeLists.txt;1;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-generic-battery-wifiradio-example "ns3-dev-generic-battery-wifiradio-example-default")
set_tests_properties(ctest-generic-battery-wifiradio-example PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/energy/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/energy/examples/CMakeLists.txt;8;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-li-ion-energy-source-example "ns3-dev-li-ion-energy-source-example-default")
set_tests_properties(ctest-li-ion-energy-source-example PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/energy/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/energy/examples/CMakeLists.txt;20;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-rv-battery-model-test "ns3-dev-rv-battery-model-test-default")
set_tests_properties(ctest-rv-battery-model-test PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/energy/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/energy/examples/CMakeLists.txt;27;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-basic-energy-model-test "ns3-dev-basic-energy-model-test-default")
set_tests_properties(ctest-basic-energy-model-test PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/energy/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/energy/examples/CMakeLists.txt;36;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/energy/examples/CMakeLists.txt;0;")
