# CMake generated Testfile for 
# Source directory: /home/ck/桌面/ns/ns-3.37/src/wifi/examples
# Build directory: /home/ck/桌面/ns/ns-3.37/src/wifi/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-wifi-phy-test "ns3-dev-wifi-phy-test-default")
set_tests_properties(ctest-wifi-phy-test PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/wifi/examples/CMakeLists.txt;1;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-test-interference-helper "ns3-dev-wifi-test-interference-helper-default")
set_tests_properties(ctest-wifi-test-interference-helper PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/wifi/examples/CMakeLists.txt;11;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-manager-example "ns3-dev-wifi-manager-example-default")
set_tests_properties(ctest-wifi-manager-example PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/wifi/examples/CMakeLists.txt;21;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-trans-example "ns3-dev-wifi-trans-example-default")
set_tests_properties(ctest-wifi-trans-example PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/wifi/examples/CMakeLists.txt;33;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-phy-configuration "ns3-dev-wifi-phy-configuration-default")
set_tests_properties(ctest-wifi-phy-configuration PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/wifi/examples/CMakeLists.txt;45;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-bianchi "ns3-dev-wifi-bianchi-default")
set_tests_properties(ctest-wifi-bianchi PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/wifi/examples/CMakeLists.txt;52;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/wifi/examples/CMakeLists.txt;0;")
