# CMake generated Testfile for 
# Source directory: /home/ck/桌面/ns/ns-3.37/src/network/examples
# Build directory: /home/ck/桌面/ns/ns-3.37/src/network/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-bit-serializer "ns3-dev-bit-serializer-default")
set_tests_properties(ctest-bit-serializer PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-header "ns3-dev-main-packet-header-default")
set_tests_properties(ctest-main-packet-header PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-tag "ns3-dev-main-packet-tag-default")
set_tests_properties(ctest-main-packet-tag PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-packet-socket-apps "ns3-dev-packet-socket-apps-default")
set_tests_properties(ctest-packet-socket-apps PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-lollipop-comparisons "ns3-dev-lollipop-comparisons-default")
set_tests_properties(ctest-lollipop-comparisons PROPERTIES  WORKING_DIRECTORY "/home/ck/桌面/ns/ns-3.37/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ck/桌面/ns/ns-3.37/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ck/桌面/ns/ns-3.37/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/ck/桌面/ns/ns-3.37/src/network/examples/CMakeLists.txt;0;")
